# Generated by Django 2.1.4 on 2018-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('conNum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='conNum')),
                ('fileName', models.CharField(max_length=100, verbose_name='fileName')),
                ('path', models.CharField(max_length=100, verbose_name='path')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('uploadTime', models.DateTimeField(verbose_name='uploadTime')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='num')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('customer', models.CharField(max_length=40, verbose_name='customer')),
                ('beginTime', models.DateTimeField(verbose_name='beginTime')),
                ('endTime', models.DateTimeField(verbose_name='endTime')),
                ('content', models.TextField(verbose_name='content')),
                ('userName', models.CharField(max_length=40, verbose_name='userName')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='num')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('tel', models.CharField(max_length=20, verbose_name='tel')),
                ('fax', models.CharField(max_length=20, verbose_name='fax')),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
                ('bank', models.CharField(max_length=50, verbose_name='bank')),
                ('account', models.CharField(max_length=50, verbose_name='account')),
                ('remark', models.CharField(max_length=200, verbose_name='remark')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False, verbose_name='num')),
                ('name', models.CharField(max_length=40, verbose_name='description')),
                ('URL', models.CharField(max_length=100, verbose_name='URL')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40, verbose_name='userName')),
                ('content', models.TextField(verbose_name='content')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('conNum', models.IntegerField(primary_key=True, serialize=False, verbose_name='conNum')),
                ('type', models.IntegerField(verbose_name='type')),
                ('state', models.IntegerField(verbose_name='state')),
                ('userName', models.CharField(max_length=40, verbose_name='userName')),
                ('content', models.TextField(verbose_name='content')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('userName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='userName')),
                ('roleName', models.CharField(max_length=20, verbose_name='roleName')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='name')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('functions', models.CharField(max_length=500, verbose_name='functions')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conNum', models.IntegerField(verbose_name='conNum')),
                ('type', models.IntegerField(verbose_name='type')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
    ]
