# Generated by Django 2.1.2 on 2018-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='beginTime',
            field=models.DateTimeField(verbose_name='beginTime'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='endTime',
            field=models.DateTimeField(verbose_name='endTime'),
        ),
    ]
