# Generated by Django 2.1.4 on 2018-12-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181212_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='num',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='num'),
        ),
    ]
